# Use Dockerized infrastructure
sudo: false
language: python
addons:
  ssh_known_hosts:
    - 35.212.189.104
  apt:
    packages:
      - sshpass
install:
# Install the dependencies
jobs:
  include:
    - name: master branch
      script: 
        - echo "Master Branch"
        - sshpass -p $SSH_PASS ssh $USER@$HOST "cd $SERVER_PATH; sudo git pull origin master"
      if: branch = master
    - name: other branches
      script:
        - echo "Staging Branch"
        - sshpass -p $SSH_PASS ssh $USER@$HOST "cd $SERVER_PATH; sudo git pull origin staging"
      if: branch != master
# script:
# [START deploy]
# Deploy the app
# - sshpass -p $SSH_PASS ssh $USER@$HOST "cd $SERVER_PATH; sudo git pull origin staging"

branches:
  only:
  - master
  - staging