# Use Dockerized infrastructure
sudo: false
language: python
addons:
  ssh_known_hosts:
    - 35.212.189.104
  apt:
    packages:
      - sshpass
install:
# Install the dependencies
script:
# [START deploy]
# Deploy the app
- sshpass -p $SSH_PASS ssh $USER@$HOST "cd $SERVER_PATH; sudo git pull origin staging"

branches:
  only:
  - master
  - staging